const experienceLevelList = ["Beginner", "Intermediate", "Expert"] as const;
const employmentTypeList = ["Full-time", "Part-time", "Contract", "Temporary", "Internship", "Volunteer", "Other"] as const;

const industriesList = [
    "Software Development",
    "Medical & Healthcare",
    "Financial Services",
    "Retail & E-commerce",
    "Manufacturing",
    "Education & Training",
    "Information Technology",
    "Real Estate",
    "Hospitality & Tourism",
    "Construction & Engineering",
    "Automotive",
    "Energy & Utilities",
    "Telecommunications",
    "Agriculture & Farming",
    "Food & Beverage",
    "Fashion & Apparel",
    "Entertainment & Media",
    "Transportation & Logistics",
    "Pharmaceuticals",
    "Consumer Electronics",
    "Professional Services",
    "Non-profit & NGO",
    "Beauty & Personal Care",
    "Fitness & Wellness",
    "Legal Services",
    "Environmental Services",
    "Aerospace & Defense",
    "Maritime & Shipping",
    "Mining & Metals",
    "Publishing & Printing",
    "Sports & Recreation",
    "Textiles & Apparel",
    "Chemicals",
    "Furniture & Home Furnishings",
    "Plastics & Rubber",
    "Packaging",
    "Paper & Forest Products",
    "Security & Investigations",
    "Market Research",
    "Human Resources",
    "Cleaning & Maintenance",
    "Veterinary",
    "Animation & Graphic Design",
    "Event Planning & Services",
    "Insurance",
    "Architecture & Planning",
    "Renewable Energy",
    "Biotechnology",
    "Art & Crafts",
    "Gaming & Interactive",
] as const;

const jobFacilitiesList = [
    "Bonus",
    "Comission",
    "Paid Overtime",
    "Medical Cover",
    "Dental Care",
    "Life Insurance",
    "Eye Care",
    "Company Car",
    "Travel Expenses",
    "Share Plan",
    "Flexible Working Hours",
    "Car Allowance",
    "Subsidized Food",
    "Shipping/Retail Discount",
    "Gym Membership",
    "Private Pension",
];

const minimumQualifications = [
    "High school diploma or equivalent",
    "Bachelor's degree in a related field",
    "Master's degree in a related field",
    "PhD in a related field",
    "Relevant certification",
    "Relevant license",
    "Relevant work experience",
    "Other",
] as const;

const questionTypeList = ["Multiple Choice", "Single Choice", "Text Answer"] as const;

const lists = {
    employmentTypeList,
    experienceLevelList,
    industriesList,
    jobFacilitiesList,
    minimumQualifications,
    questionTypeList,
} as const;

export const getList = <T extends keyof typeof lists>(list: T) => lists[list];
