import { Job } from "./prisma/generated/zod";

// prettier-ignore

const testJobs: Job[] = [
    {
        id: "c29d5a83-4f8e-411b-a4b8-3f1b0f2b5e3d",
        industry: "Information_Technology",
        title: "Senior Software Engineer",
        location: "Berlin, Germany",
        locationPreference: "REMOTE",
        type: "Engineering",
        employmentType: "FULL_TIME",
        experienceLevel: "EXPERT",
        minimumQualification: "BACHELOR",
        visaSponsorship: true,
        salaryType: "RANGE",
        salaryMin: 70000,
        salaryMax: 100000,
        salaryCurrency: "EUR",
        salaryInterval: "YEARLY",
        facilities: ["Remote work options", "Health insurance", "Gym membership"],
        description: "As a Senior Software Engineer, you will be responsible for developing high-quality software solutions. You should have a strong background in software development, excellent problem-solving skills, and the ability to work collaboratively in a team environment.",
        responsibilities: "Develop and maintain advanced software applications. Write clean, efficient, and maintainable code. Collaborate with cross-functional teams to define, design, and ship new features.",
        requirements: "Bachelor's degree in Computer Science or related field. 5+ years of experience in software development. Proficiency in Java, Spring Boot, and Microservices.",
        createdAt: new Date("2024-02-01T09:00:00.000Z"),
        updatedAt: new Date("2024-02-01T09:00:00.000Z"),
        tags: ["Java"],
    },
    {
        id: "asd-4f8e-411b-a4b8-3f1b0f2b5e3d",
        industry: "Information_Technology",
        title: "Senior Software Engineer",
        location: "Berlin, Germany",
        locationPreference: "ONSITE",
        type: "Engineering",
        employmentType: "FULL_TIME",
        experienceLevel: "INTERMEDIATE",
        minimumQualification: "BACHELOR",
        visaSponsorship: true,
        salaryType: "RANGE",
        salaryMin: 70000,
        salaryMax: 100000,
        salaryCurrency: "EUR",
        salaryInterval: "YEARLY",
        facilities: ["Remote work options", "Health insurance", "Gym membership"],
        description: "As a Senior Software Engineer, you will be responsible for developing high-quality software solutions. You should have a strong background in software development, excellent problem-solving skills, and the ability to work collaboratively in a team environment.",
        responsibilities: "Develop and maintain advanced software applications. Write clean, efficient, and maintainable code. Collaborate with cross-functional teams to define, design, and ship new features.",
        requirements: "Bachelor's degree in Computer Science or related field. 5+ years of experience in software development. Proficiency in Java, Spring Boot, and Microservices.",
        createdAt: new Date("2024-02-01T09:00:00.000Z"),
        updatedAt: new Date("2024-02-01T09:00:00.000Z"),
        tags: ["Java"],
    },
    {
        id: "c29d5a83-4f8e-411b-a4b8-3f1b0f2b5e3d",
        industry: "Information_Technology",
        title: "Senior Software Engineer",
        location: "Berlin, France",
        locationPreference: "REMOTE",
        type: "Engineering",
        employmentType: "FULL_TIME",
        experienceLevel: "EXPERT",
        minimumQualification: "NONE",
        visaSponsorship: true,
        salaryType: "FIXED",
        salaryMin: 70000,
        salaryMax: 100000,
        salaryCurrency: "INR",
        salaryInterval: "YEARLY",
        facilities: ["Remote work options", "Health insurance", "Gym membership"],
        description: "As a Senior Software Engineer, you will be responsible for developing high-quality software solutions. You should have a strong background in software development, excellent problem-solving skills, and the ability to work collaboratively in a team environment.",
        responsibilities: "Develop and maintain advanced software applications. Write clean, efficient, and maintainable code. Collaborate with cross-functional teams to define, design, and ship new features.",
        requirements: "Bachelor's degree in Computer Science or related field. 5+ years of experience in software development. Proficiency in Java, Spring Boot, and Microservices.",
        createdAt: new Date("2024-02-01T09:00:00.000Z"),
        updatedAt: new Date("2024-02-01T09:00:00.000Z"),
        tags: ["Java"],
    },
    {
        id: "c29d5a83-4f8e-411b-a4b8-3f1b0f2b5e3d",
        industry: "Information_Technology",
        title: "Senior Software Engineer",
        location: "Berlin, France",
        locationPreference: "REMOTE",
        type: "Engineering",
        employmentType: "FULL_TIME",
        experienceLevel: "EXPERT",
        minimumQualification: "NONE",
        visaSponsorship: true,
        salaryType: "FIXED",
        salaryMin: 70000,
        salaryMax: 100000,
        salaryCurrency: "INR",
        salaryInterval: "YEARLY",
        facilities: ["Remote work options", "Health insurance", "Gym membership"],
        description: "As a Senior Software Engineer, you will be responsible for developing high-quality software solutions. You should have a strong background in software development, excellent problem-solving skills, and the ability to work collaboratively in a team environment.",
        responsibilities: "Develop and maintain advanced software applications. Write clean, efficient, and maintainable code. Collaborate with cross-functional teams to define, design, and ship new features.",
        requirements: "Bachelor's degree in Computer Science or related field. 5+ years of experience in software development. Proficiency in Java, Spring Boot, and Microservices.",
        createdAt: new Date("2024-02-01T09:00:00.000Z"),
        updatedAt: new Date("2024-02-01T09:00:00.000Z"),
        tags: ["Java"],
    },
    {
        id: "c29d5a83-4f8e-411b-a4b8-3f1b0f2b5e3d",
        industry: "Information_Technology",
        title: "Senior Software Engineer",
        location: "Berlin, France",
        locationPreference: "REMOTE",
        type: "Engineering",
        employmentType: "FULL_TIME",
        experienceLevel: "EXPERT",
        minimumQualification: "NONE",
        visaSponsorship: true,
        salaryType: "FIXED",
        salaryMin: 70000,
        salaryMax: 100000,
        salaryCurrency: "INR",
        salaryInterval: "YEARLY",
        facilities: ["Remote work options", "Health insurance", "Gym membership"],
        description: "As a Senior Software Engineer, you will be responsible for developing high-quality software solutions. You should have a strong background in software development, excellent problem-solving skills, and the ability to work collaboratively in a team environment.",
        responsibilities: "Develop and maintain advanced software applications. Write clean, efficient, and maintainable code. Collaborate with cross-functional teams to define, design, and ship new features.",
        requirements: "Bachelor's degree in Computer Science or related field. 5+ years of experience in software development. Proficiency in Java, Spring Boot, and Microservices.",
        createdAt: new Date("2024-02-01T09:00:00.000Z"),
        updatedAt: new Date("2024-02-01T09:00:00.000Z"),
        tags: ["Java"],
    },
];

const tests = { testJobs: testJobs } as const;

export const getTest = <T extends keyof typeof tests>(test: T) => {
    return tests[test];
};
